# Generated by Django 4.2.4 on 2023-09-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
